[build.env]
passthrough = [
    "CARGO_HOME",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "PATH=/root/.cargo/bin:$PATH rustup toolchain install nightly --component rust-src",
    "PATH=/root/.cargo/bin:$PATH cargo install bpf-linker --locked",
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "PATH=/root/.cargo/bin:$PATH rustup toolchain install nightly --component rust-src",
    "PATH=/root/.cargo/bin:$PATH cargo install bpf-linker --locked",
]
